// Code generated by MockGen. DO NOT EDIT.
// Source: shopping_item_usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/sakaguchi-0725/echo-onion-arch/domain/model"
)

// MockShoppingItemUsecase is a mock of ShoppingItemUsecase interface.
type MockShoppingItemUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockShoppingItemUsecaseMockRecorder
}

// MockShoppingItemUsecaseMockRecorder is the mock recorder for MockShoppingItemUsecase.
type MockShoppingItemUsecaseMockRecorder struct {
	mock *MockShoppingItemUsecase
}

// NewMockShoppingItemUsecase creates a new mock instance.
func NewMockShoppingItemUsecase(ctrl *gomock.Controller) *MockShoppingItemUsecase {
	mock := &MockShoppingItemUsecase{ctrl: ctrl}
	mock.recorder = &MockShoppingItemUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShoppingItemUsecase) EXPECT() *MockShoppingItemUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShoppingItemUsecase) Create(ctx context.Context, userID, category, description string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, category, description)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShoppingItemUsecaseMockRecorder) Create(ctx, userID, category, description interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShoppingItemUsecase)(nil).Create), ctx, userID, category, description)
}

// Delete mocks base method.
func (m *MockShoppingItemUsecase) Delete(ctx context.Context, userID string, itemID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShoppingItemUsecaseMockRecorder) Delete(ctx, userID, itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShoppingItemUsecase)(nil).Delete), ctx, userID, itemID)
}

// FindAll mocks base method.
func (m *MockShoppingItemUsecase) FindAll(ctx context.Context, userID string) ([]*model.ShoppingItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, userID)
	ret0, _ := ret[0].([]*model.ShoppingItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockShoppingItemUsecaseMockRecorder) FindAll(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockShoppingItemUsecase)(nil).FindAll), ctx, userID)
}
