// Code generated by MockGen. DO NOT EDIT.
// Source: shopping_item_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/sakaguchi-0725/echo-onion-arch/domain/model"
)

// MockShoppingItemRepository is a mock of ShoppingItemRepository interface.
type MockShoppingItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShoppingItemRepositoryMockRecorder
}

// MockShoppingItemRepositoryMockRecorder is the mock recorder for MockShoppingItemRepository.
type MockShoppingItemRepositoryMockRecorder struct {
	mock *MockShoppingItemRepository
}

// NewMockShoppingItemRepository creates a new mock instance.
func NewMockShoppingItemRepository(ctrl *gomock.Controller) *MockShoppingItemRepository {
	mock := &MockShoppingItemRepository{ctrl: ctrl}
	mock.recorder = &MockShoppingItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShoppingItemRepository) EXPECT() *MockShoppingItemRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockShoppingItemRepository) Delete(userID model.UserID, itemID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", userID, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShoppingItemRepositoryMockRecorder) Delete(userID, itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShoppingItemRepository)(nil).Delete), userID, itemID)
}

// FindAll mocks base method.
func (m *MockShoppingItemRepository) FindAll(userID model.UserID) ([]*model.ShoppingItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", userID)
	ret0, _ := ret[0].([]*model.ShoppingItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockShoppingItemRepositoryMockRecorder) FindAll(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockShoppingItemRepository)(nil).FindAll), userID)
}

// FindByID mocks base method.
func (m *MockShoppingItemRepository) FindByID(id string) (*model.ShoppingItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*model.ShoppingItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockShoppingItemRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockShoppingItemRepository)(nil).FindByID), id)
}

// Insert mocks base method.
func (m *MockShoppingItemRepository) Insert(v *model.ShoppingItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockShoppingItemRepositoryMockRecorder) Insert(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockShoppingItemRepository)(nil).Insert), v)
}

// Update mocks base method.
func (m *MockShoppingItemRepository) Update(v *model.ShoppingItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockShoppingItemRepositoryMockRecorder) Update(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockShoppingItemRepository)(nil).Update), v)
}
